# Generated by Django 4.2.30 on 2026-05-13 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslider',
            name='image',
            field=models.ImageField(upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='image',
            field=models.ImageField(upload_to='packages/'),
        ),
    ]
