# Generated by Django 4.2.30 on 2026-05-13 05:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_alter_heroslider_image_alter_tourpackage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslider',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
