# Generated by Django 4.2.30 on 2026-05-15 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_alter_heroslider_image_alter_tourpackage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='exclusions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='inclusions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='itinerary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=200)),
                ('guest_email', models.EmailField(max_length=254)),
                ('guest_phone', models.CharField(max_length=20)),
                ('travel_date', models.DateField()),
                ('number_of_guests', models.PositiveIntegerField()),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='packages.tourpackage')),
            ],
        ),
    ]
