# Generated by Django 4.2.30 on 2026-05-19 10:22

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogpost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image_link',
            field=models.URLField(blank=True, help_text='Or paste a direct image URL link instead of uploading an image file', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='image_link',
            field=models.URLField(blank=True, help_text='Or paste a direct image URL link instead of uploading an image file', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
